### ISSUE TITLE
是否重开仓库，issue请求的仓库主体

### ISSUE THREAD

**Issue by Zeuyel** [sqsssq/ZUFE-Thesis#1]
你好，感谢你的工作为我减少了造轮子的时间！

不过我发现[这个项目](https://github.com/2431052785/zufe-latex) 和你的极其类似，这是你的新项目吗？但是我看那个帐号不怎么commit，issue和PR是否还是在这个仓库提？

顺颂钧安！

**Comment by sqsssq** [comment]
感谢您，很高兴这能为您有所帮助，那个项目不是我的，是同校后辈做的，并且没有知会我
如果有新的issue和PR，请提交在这个项目上，谢谢。

**Comment by Zeuyel** [comment]
好的，感谢学长回复！原来是这样。原以为是学长重新更新了bst文件采用了清华的样式，进行了进一步完善，我使用Latex比较早，基本上前面的课程论文都是依靠学长的工作，故来此咨询并表示感谢。Anyway，原本的项目就已经很完善了，帮助了我很多。

另，他没有写ReadMe说明项目继承关系在[宣传](https://mp.weixin.qq.com/s/p9tAx-b_8dyfBYwe6lDajw)中也没有提及，最后导致了我的误解。了解后竟然是这样，对这种摘桃子的行为让人不齿！

**Comment by sqsssq** [comment]
感谢！
